services:
  mysql:
    container_name: prod-database
    image: mysql:8.0
    env_file:
      - ./backend/.env.prod
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - dispatch-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
    env_file:
      - ./backend/.env.prod
    depends_on:
      - mysql
    networks:
      - dispatch-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    env_file:
      - ./frontend/.env.prod
    environment:
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - dispatch-network

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

volumes:
  mysql_data:

networks:
  dispatch-network:
    driver: bridge